### PR TITLE
Hello, this is a Log4J2 appender experiment

### PR DESCRIPTION
**Pull request by joshuadavis**
Thought I'd make a Log4J2 appender for Logentries, since I'm using Log4J2.

### CODE REVIEW

**Comment by apiraino** [comment]
Hello,

any news concerning this pull request?
I've been keeping an eye on this because it would be nice to have it for a project I'm working on.
I'd like to link Logentries but I'm using Log4j2. Else I need to find another way of logging without Logentries.

thanks

**Comment by joshuadavis** [comment]
I haven't heard anything yet, but I'm using this code in production and it seems to be working well.

**Comment by raupachz** [comment]
Unfortunately there is not much feedback from the Logentries Team. I also wrote a Logentries appender, however for JUL. Its running in production for months without any troubles.

**Comment by samjamesobrien** [comment]
Sorry this was not evaluated sooner guys, I am going to have a look at the open pull requests for this library in the coming days.

**Comment by joshuadavis** [comment]
Great!

**Comment by apiraino** [comment]
:+1:

**Comment by samjamesobrien** [comment]
:+1:

**Comment by samjamesobrien** [comment]
@joshuadavis could you provide a sample configuration to include in the logging library?

**Comment by samjamesobrien** [comment]
@joshuadavis disregard, I put one together.

**Comment by joshuadavis** [comment]
Okay, great!   It's pretty straightforward.

<Logentries name="logentries"
            token="aaaaaaaa-bbbb-cccc-dddd-fffffffff"
            logID="foo"
            location="bar"
            logHostName="true">
    <PatternLayout pattern="blah"/>
</Logentries>

**Comment by apiraino** [comment]
My log4j2xml looks like this:

```
<?xml version="1.0" encoding="UTF-8"?>
<Configuration>
    <properties>
        <property name="logPath">/tmp/</property>
        <property name="logFileName">MyLogFile.log</property>
        <property name="logRollingFileName">MyLogFile-rolling.log</property>
        <property name="pattern">%d %-5p [%t] %C{2} (%F:%L) - %m%n</property>
    </properties>
    <Appenders>
        <Console name="STDOUT" target="SYSTEM_OUT">
            <PatternLayout pattern="${pattern}"/>
        </Console>
        <File name="MyAgentLog" fileName="${pattern}${logFileName}">
            <PatternLayout pattern="${pattern}"/>
        </File>
        <Logentries name="le"
                     token="${env:LOGENTRIES_TOKEN}"
                     debug="false">
            <PatternLayout pattern="${pattern}"/>
        </Logentries>
        <RollingFile name="roll"
                     fileName="${logPath}${logRollingFileName}"
                     filePattern="${logPath}${logRollingFileName}-%i.log.gz">
            <PatternLayout pattern="${pattern}" />
            <Policies>
                <SizeBasedTriggeringPolicy size="10 MB"/>
            </Policies>
        </RollingFile>
    </Appenders>
    <Loggers>
        <Logger name="org.apache.log4j.xml" level="info"/>
        <Root level="debug">
            <AppenderRef ref="le"/>
        </Root>
    </Loggers>
</Configuration>
```

The Logentries token is set from ENV, e.g.:
export LOGENTRIES_TOKEN=AAABBBCCC

You have four appenders available: console, File, RollingFile, Logentries. Only Logentries ("le") is enabled.

**Comment by samjamesobrien** [comment]
Thanks guys, I will include these in the sample files.

**Pull request merged**
